#!/usr/bin/env bash
# This script configures your Nginx server so that /redirect_me is redirecting to another page

apt-get update
apt-get install nginx -y
echo "Hello World!" > /var/www/html/index.html
echo "server {
	listen 80;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html;
	location /redirect_me {
		return 301 https://github.com/kipngenokevin;
	}
}
" > /etc/nginx/sites-available/default
service nginx restart
