#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=2.0.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend kcodev.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 240155-web-01 54.162.77.111:80
        server 240155-web-02 100.24.205.250:80
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
