#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 20 and
# displays 4 and then bad luck from China
# displays 9 and then bad luck from Japan
# displays 17 and then bad luck from Italy
counter=1
while [ $counter -le 20 ]
do
	case $counter in
		4)
			echo "$counter"
			echo "bad luck from China"
			;;
		9)
			echo "$counter"
			echo "bad luck from Japan"
			;;
		17)
			echo "$counter"
			echo "bad luck from Italy"
			;;
		*)
			echo "$counter"
			;;
	esac
	((counter++))
done
